autorun : PopUpWindow.class
	# font=Segoe UI
	env NOTIFICATION_OPTIONS='background-color=#faac14 timeout=10 window-position=N font-size=24 fly-in-duration=1s' java -cp . PopUpWindow "Touch the YubiKey"

PopUpWindows.class : PopUpWindows.java
	javac PopUpWindow.java
