autorun : PopUpWindow.class
	env NOTIFICATION_OPTIONS='a=1+2=3 b=x timeout=10 window-position=C' GPG2F_DEFAULT_NOTIFICATION_OPTIONS='b=default_b c=default_c'  java -cp . PopUpWindow "message\nline 2\nline 3"

PopUpWindows.class : PopUpWindows.java
	javac PopUpWindow.java
