autorun : PopUpWindow.class
	env NOTIFICATION_OPTIONS='a=1+2=3 b=x timeout=10 window-position=N font=Segoe UI font-size=24 fly-in-duration=1s' GPG2F_DEFAULT_NOTIFICATION_OPTIONS='b=default_b c=default_c'  java -cp . PopUpWindow "message\nline 2\nline 3"

PopUpWindows.class : PopUpWindows.java
	javac PopUpWindow.java
